// Code generated by protoc-gen-go. DO NOT EDIT.
// source: truck.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_truck_69032e202ee4ed7e, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_truck_69032e202ee4ed7e, []int{1}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Truck struct {
	ID                   string    `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Location             *Location `protobuf:"bytes,3,opt,name=Location,json=location,proto3" json:"Location,omitempty"`
	Timestamp            int64     `protobuf:"varint,4,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Truck) Reset()         { *m = Truck{} }
func (m *Truck) String() string { return proto.CompactTextString(m) }
func (*Truck) ProtoMessage()    {}
func (*Truck) Descriptor() ([]byte, []int) {
	return fileDescriptor_truck_69032e202ee4ed7e, []int{2}
}
func (m *Truck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Truck.Unmarshal(m, b)
}
func (m *Truck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Truck.Marshal(b, m, deterministic)
}
func (dst *Truck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Truck.Merge(dst, src)
}
func (m *Truck) XXX_Size() int {
	return xxx_messageInfo_Truck.Size(m)
}
func (m *Truck) XXX_DiscardUnknown() {
	xxx_messageInfo_Truck.DiscardUnknown(m)
}

var xxx_messageInfo_Truck proto.InternalMessageInfo

func (m *Truck) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Truck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Truck) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Truck) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Truck                *Truck   `protobuf:"bytes,2,opt,name=truck,proto3" json:"truck,omitempty"`
	Trucks               []*Truck `protobuf:"bytes,3,rep,name=trucks,proto3" json:"trucks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_truck_69032e202ee4ed7e, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetTruck() *Truck {
	if m != nil {
		return m.Truck
	}
	return nil
}

func (m *Response) GetTrucks() []*Truck {
	if m != nil {
		return m.Trucks
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*Location)(nil), "proto.Location")
	proto.RegisterType((*Truck)(nil), "proto.Truck")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TruckServiceClient is the client API for TruckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TruckServiceClient interface {
	Create(ctx context.Context, in *Truck, opts ...grpc.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteAll(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type truckServiceClient struct {
	cc *grpc.ClientConn
}

func NewTruckServiceClient(cc *grpc.ClientConn) TruckServiceClient {
	return &truckServiceClient{cc}
}

func (c *truckServiceClient) Create(ctx context.Context, in *Truck, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TruckService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckServiceClient) GetAll(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TruckService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TruckService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckServiceClient) DeleteAll(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TruckService/DeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TruckServiceServer is the server API for TruckService service.
type TruckServiceServer interface {
	Create(context.Context, *Truck) (*Response, error)
	GetAll(context.Context, *GetRequest) (*Response, error)
	Get(context.Context, *GetRequest) (*Response, error)
	DeleteAll(context.Context, *GetRequest) (*Response, error)
}

func RegisterTruckServiceServer(s *grpc.Server, srv TruckServiceServer) {
	s.RegisterService(&_TruckService_serviceDesc, srv)
}

func _TruckService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Truck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TruckService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckServiceServer).Create(ctx, req.(*Truck))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TruckService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckServiceServer).GetAll(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TruckService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckService_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckServiceServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TruckService/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckServiceServer).DeleteAll(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TruckService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TruckService",
	HandlerType: (*TruckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TruckService_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _TruckService_GetAll_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TruckService_Get_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _TruckService_DeleteAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "truck.proto",
}

func init() { proto.RegisterFile("truck.proto", fileDescriptor_truck_69032e202ee4ed7e) }

var fileDescriptor_truck_69032e202ee4ed7e = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xcd, 0x6a, 0xf3, 0x30,
	0x10, 0xfc, 0x14, 0x27, 0xfe, 0xac, 0x4d, 0x68, 0xe9, 0x9e, 0x4c, 0xc8, 0xc1, 0x88, 0x1e, 0x52,
	0x02, 0x81, 0xa6, 0x4f, 0x50, 0x6a, 0x08, 0x85, 0xd2, 0x83, 0x9a, 0x17, 0x50, 0x9d, 0xa5, 0x98,
	0xca, 0x56, 0x6a, 0x6f, 0xf2, 0x8e, 0x7d, 0xab, 0x52, 0x39, 0xaa, 0xe9, 0xcf, 0x21, 0x27, 0x69,
	0x67, 0x66, 0x77, 0x46, 0x5a, 0x18, 0x73, 0xb3, 0x2f, 0x5e, 0x97, 0xbb, 0xc6, 0xb1, 0xc3, 0x91,
	0x3f, 0xd4, 0x0c, 0x60, 0x4d, 0xac, 0xe9, 0x6d, 0x4f, 0x2d, 0xe3, 0x19, 0x0c, 0xee, 0xf3, 0x54,
	0x64, 0x62, 0x2e, 0xf5, 0xa0, 0xcc, 0x55, 0x0e, 0xc9, 0x83, 0x2b, 0x0c, 0x97, 0xae, 0xc6, 0x29,
	0x24, 0xd6, 0x70, 0xc9, 0xfb, 0x2d, 0x79, 0x85, 0xd0, 0x5f, 0x35, 0xce, 0x40, 0x5a, 0x57, 0xbf,
	0x74, 0xe4, 0xc0, 0x93, 0x3d, 0xa0, 0x0e, 0x30, 0xda, 0x7c, 0x3a, 0xff, 0x1c, 0x8f, 0x08, 0xc3,
	0x47, 0x53, 0x75, 0x1d, 0x52, 0x0f, 0x6b, 0x53, 0x11, 0x2e, 0x7a, 0xcb, 0x34, 0xca, 0xc4, 0x7c,
	0xbc, 0x3a, 0xef, 0x12, 0x2f, 0x03, 0xac, 0x13, 0x1b, 0x32, 0xcd, 0x40, 0x6e, 0xca, 0x8a, 0x5a,
	0x36, 0xd5, 0x2e, 0x1d, 0x66, 0x62, 0x1e, 0x69, 0xc9, 0x01, 0x50, 0x35, 0x24, 0x9a, 0xda, 0x9d,
	0xab, 0x5b, 0xc2, 0x14, 0xfe, 0x17, 0x0d, 0x19, 0xa6, 0xad, 0xf7, 0x4f, 0x74, 0x28, 0x51, 0xc1,
	0xc8, 0xff, 0x8b, 0x4f, 0x31, 0x5e, 0x4d, 0x8e, 0x6e, 0x3e, 0xb1, 0xee, 0x28, 0xbc, 0x84, 0xd8,
	0x5f, 0xda, 0x34, 0xca, 0xa2, 0x5f, 0xa2, 0x23, 0xb7, 0x7a, 0x17, 0x30, 0xf1, 0xc8, 0x13, 0x35,
	0x87, 0xb2, 0x20, 0xbc, 0x82, 0xf8, 0xce, 0xbb, 0xe0, 0xb7, 0x86, 0x69, 0x78, 0x51, 0x48, 0xa7,
	0xfe, 0xe1, 0x12, 0xe2, 0x35, 0xf1, 0xad, 0xb5, 0x78, 0x71, 0x24, 0xfb, 0xb5, 0xfc, 0xa5, 0x5f,
	0x40, 0xb4, 0x26, 0x3e, 0x51, 0x7c, 0x0d, 0x32, 0x27, 0x4b, 0x4c, 0x27, 0xcf, 0x7f, 0x8e, 0x3d,
	0x72, 0xf3, 0x11, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x61, 0xd1, 0x06, 0x34, 0x02, 0x00, 0x00,
}
